/**
 * generated by Xtext 2.20.0
 */
package org.mofgen.ui.contentassist;

import org.mofgen.ui.contentassist.AbstractMGLangProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MGLangProposalProvider extends AbstractMGLangProposalProvider {
}
