/*
 * generated by Xtext 2.20.0
 */
package org.mofgen.ide

import org.moflon.mofgen.ide.AbstractMGLangIdeModule

/**
 * Use this class to register ide components.
 */
class MGLangIdeModule extends AbstractMGLangIdeModule {
}
