/*
 * generated by Xtext 2.20.0
 */
package org.moflon.mofgen


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MGLangStandaloneSetup extends MGLangStandaloneSetupGenerated {

	def static void doSetup() {
		new MGLangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
