/**
 * generated by Xtext 2.20.0
 */
package org.mofgen.mGLang.impl;

import org.eclipse.emf.ecore.EClass;

import org.mofgen.mGLang.MGLangPackage;
import org.mofgen.mGLang.NodeReferenceOrAssignmentOrControlFlow;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Node Reference Or Assignment Or Control Flow</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NodeReferenceOrAssignmentOrControlFlowImpl extends SwitchExpressionImpl implements NodeReferenceOrAssignmentOrControlFlow
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NodeReferenceOrAssignmentOrControlFlowImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MGLangPackage.Literals.NODE_REFERENCE_OR_ASSIGNMENT_OR_CONTROL_FLOW;
  }

} //NodeReferenceOrAssignmentOrControlFlowImpl
