<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="typeModel" nsURI="http://www.example.org/typeModel" nsPrefix="typeModel">
  <eClassifiers xsi:type="ecore:EClass" name="Number" abstract="true" eSuperTypes="#//Primitive"/>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//Primitive"/>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//Primitive"/>
  <eClassifiers xsi:type="ecore:EClass" name="Primitive" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enum"/>
  <eClassifiers xsi:type="ecore:EClass" name="Map" eSuperTypes="#//Collection">
    <eOperations name="get" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eParameters name="key" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="put" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="key" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="value" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="containsKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="key" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="containsValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="value" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="isEmpty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getKeyToEntry" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eParameters name="entry" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="remove" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eParameters name="key" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keys" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="#//Collection">
    <eOperations name="get" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eParameters name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="add" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="obj" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="contains" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="obj" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="indexOf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eParameters name="obj" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="isEmpty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="removeAt" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eParameters name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="remove" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="obj" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="addAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="coll" eType="#//List"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collection" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="Double" eSuperTypes="#//Number"/>
  <eClassifiers xsi:type="ecore:EClass" name="Integer" eSuperTypes="#//Number"/>
</ecore:EPackage>
