/**
 * generated by Xtext 2.20.0
 */
package org.mofgen.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.mofgen.MGLangRuntimeModule;
import org.mofgen.MGLangStandaloneSetup;
import org.mofgen.ide.MGLangIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MGLangIdeSetup extends MGLangStandaloneSetup {
  @Override
  public Injector createInjector() {
    MGLangRuntimeModule _mGLangRuntimeModule = new MGLangRuntimeModule();
    MGLangIdeModule _mGLangIdeModule = new MGLangIdeModule();
    return Guice.createInjector(Modules2.mixin(_mGLangRuntimeModule, _mGLangIdeModule));
  }
}
