/**
 * generated by Xtext 2.20.0
 */
package org.mofgen.mGLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mofgen.mGLang.BooleanLiteral#isVal <em>Val</em>}</li>
 * </ul>
 *
 * @see org.mofgen.mGLang.MGLangPackage#getBooleanLiteral()
 * @model
 * @generated
 */
public interface BooleanLiteral extends Literal
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(boolean)
   * @see org.mofgen.mGLang.MGLangPackage#getBooleanLiteral_Val()
   * @model
   * @generated
   */
  boolean isVal();

  /**
   * Sets the value of the '{@link org.mofgen.mGLang.BooleanLiteral#isVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #isVal()
   * @generated
   */
  void setVal(boolean value);

} // BooleanLiteral
