/**
 * generated by Xtext 2.20.0
 */
package org.mofgen.mGLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Collection</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.mofgen.mGLang.MGLangPackage#getCollection()
 * @model
 * @generated
 */
public interface Collection extends PatternCommand, GeneratorExpression, RefType, SwitchExpression
{
} // Collection
