/**
 * generated by Xtext 2.20.0
 */
package org.mofgen.mGLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For Head</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mofgen.mGLang.ForHead#getIteratorVar <em>Iterator Var</em>}</li>
 * </ul>
 *
 * @see org.mofgen.mGLang.MGLangPackage#getForHead()
 * @model
 * @generated
 */
public interface ForHead extends EObject
{
  /**
   * Returns the value of the '<em><b>Iterator Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Iterator Var</em>' attribute.
   * @see #setIteratorVar(String)
   * @see org.mofgen.mGLang.MGLangPackage#getForHead_IteratorVar()
   * @model
   * @generated
   */
  String getIteratorVar();

  /**
   * Sets the value of the '{@link org.mofgen.mGLang.ForHead#getIteratorVar <em>Iterator Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Iterator Var</em>' attribute.
   * @see #getIteratorVar()
   * @generated
   */
  void setIteratorVar(String value);

} // ForHead
