/**
 * generated by Xtext 2.20.0
 */
package org.mofgen.mGLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>General For Head</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mofgen.mGLang.GeneralForHead#getRange <em>Range</em>}</li>
 * </ul>
 *
 * @see org.mofgen.mGLang.MGLangPackage#getGeneralForHead()
 * @model
 * @generated
 */
public interface GeneralForHead extends ForHead
{
  /**
   * Returns the value of the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Range</em>' containment reference.
   * @see #setRange(ForRange)
   * @see org.mofgen.mGLang.MGLangPackage#getGeneralForHead_Range()
   * @model containment="true"
   * @generated
   */
  ForRange getRange();

  /**
   * Sets the value of the '{@link org.mofgen.mGLang.GeneralForHead#getRange <em>Range</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Range</em>' containment reference.
   * @see #getRange()
   * @generated
   */
  void setRange(ForRange value);

} // GeneralForHead
