/**
 * generated by Xtext 2.20.0
 */
package org.mofgen.mGLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gen Pattern Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mofgen.mGLang.GenPatternCall#getCalledPattern <em>Called Pattern</em>}</li>
 *   <li>{@link org.mofgen.mGLang.GenPatternCall#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see org.mofgen.mGLang.MGLangPackage#getGenPatternCall()
 * @model
 * @generated
 */
public interface GenPatternCall extends EObject
{
  /**
   * Returns the value of the '<em><b>Called Pattern</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Called Pattern</em>' reference.
   * @see #setCalledPattern(Pattern)
   * @see org.mofgen.mGLang.MGLangPackage#getGenPatternCall_CalledPattern()
   * @model
   * @generated
   */
  Pattern getCalledPattern();

  /**
   * Sets the value of the '{@link org.mofgen.mGLang.GenPatternCall#getCalledPattern <em>Called Pattern</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Called Pattern</em>' reference.
   * @see #getCalledPattern()
   * @generated
   */
  void setCalledPattern(Pattern value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link org.mofgen.mGLang.PatternObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see org.mofgen.mGLang.MGLangPackage#getGenPatternCall_Params()
   * @model containment="true"
   * @generated
   */
  EList<PatternObject> getParams();

} // GenPatternCall
