/**
 * generated by Xtext 2.20.0
 */
package org.mofgen.mGLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mofgen.mGLang.IfBody#getCommands <em>Commands</em>}</li>
 * </ul>
 *
 * @see org.mofgen.mGLang.MGLangPackage#getIfBody()
 * @model
 * @generated
 */
public interface IfBody extends EObject
{
  /**
   * Returns the value of the '<em><b>Commands</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands</em>' containment reference.
   * @see #setCommands(GenCommandBlock)
   * @see org.mofgen.mGLang.MGLangPackage#getIfBody_Commands()
   * @model containment="true"
   * @generated
   */
  GenCommandBlock getCommands();

  /**
   * Sets the value of the '{@link org.mofgen.mGLang.IfBody#getCommands <em>Commands</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Commands</em>' containment reference.
   * @see #getCommands()
   * @generated
   */
  void setCommands(GenCommandBlock value);

} // IfBody
