/**
 * generated by Xtext 2.20.0
 */
package org.mofgen.mGLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Else Case</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mofgen.mGLang.IfElseCase#getVal <em>Val</em>}</li>
 *   <li>{@link org.mofgen.mGLang.IfElseCase#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.mofgen.mGLang.MGLangPackage#getIfElseCase()
 * @model
 * @generated
 */
public interface IfElseCase extends EObject
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' containment reference.
   * @see #setVal(ArithmeticExpression)
   * @see org.mofgen.mGLang.MGLangPackage#getIfElseCase_Val()
   * @model containment="true"
   * @generated
   */
  ArithmeticExpression getVal();

  /**
   * Sets the value of the '{@link org.mofgen.mGLang.IfElseCase#getVal <em>Val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' containment reference.
   * @see #getVal()
   * @generated
   */
  void setVal(ArithmeticExpression value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(CaseBody)
   * @see org.mofgen.mGLang.MGLangPackage#getIfElseCase_Body()
   * @model containment="true"
   * @generated
   */
  CaseBody getBody();

  /**
   * Sets the value of the '{@link org.mofgen.mGLang.IfElseCase#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(CaseBody value);

} // IfElseCase
