/**
 * generated by Xtext 2.20.0
 */
package org.mofgen.mGLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.mofgen.mGLang.MGLangPackage#getIfStatement()
 * @model
 * @generated
 */
public interface IfStatement extends GeneratorCommand
{
} // IfStatement
