/**
 * generated by Xtext 2.20.0
 */
package org.mofgen.mGLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.mofgen.mGLang.MGLangPackage#getMapAssignment()
 * @model
 * @generated
 */
public interface MapAssignment extends Map
{
} // MapAssignment
