/**
 * generated by Xtext 2.20.0
 */
package org.mofgen.mGLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ref Or Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mofgen.mGLang.RefOrCall#getRef <em>Ref</em>}</li>
 *   <li>{@link org.mofgen.mGLang.RefOrCall#getTarget <em>Target</em>}</li>
 *   <li>{@link org.mofgen.mGLang.RefOrCall#getParams <em>Params</em>}</li>
 *   <li>{@link org.mofgen.mGLang.RefOrCall#isBracesSet <em>Braces Set</em>}</li>
 * </ul>
 *
 * @see org.mofgen.mGLang.MGLangPackage#getRefOrCall()
 * @model
 * @generated
 */
public interface RefOrCall extends ListAssignment, MapAssignment, ArithmeticExpression
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(EObject)
   * @see org.mofgen.mGLang.MGLangPackage#getRefOrCall_Ref()
   * @model
   * @generated
   */
  EObject getRef();

  /**
   * Sets the value of the '{@link org.mofgen.mGLang.RefOrCall#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(EObject value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' containment reference.
   * @see #setTarget(RefOrCall)
   * @see org.mofgen.mGLang.MGLangPackage#getRefOrCall_Target()
   * @model containment="true"
   * @generated
   */
  RefOrCall getTarget();

  /**
   * Sets the value of the '{@link org.mofgen.mGLang.RefOrCall#getTarget <em>Target</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' containment reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(RefOrCall value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference.
   * @see #setParams(RefParams)
   * @see org.mofgen.mGLang.MGLangPackage#getRefOrCall_Params()
   * @model containment="true"
   * @generated
   */
  RefParams getParams();

  /**
   * Sets the value of the '{@link org.mofgen.mGLang.RefOrCall#getParams <em>Params</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Params</em>' containment reference.
   * @see #getParams()
   * @generated
   */
  void setParams(RefParams value);

  /**
   * Returns the value of the '<em><b>Braces Set</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Braces Set</em>' attribute.
   * @see #setBracesSet(boolean)
   * @see org.mofgen.mGLang.MGLangPackage#getRefOrCall_BracesSet()
   * @model
   * @generated
   */
  boolean isBracesSet();

  /**
   * Sets the value of the '{@link org.mofgen.mGLang.RefOrCall#isBracesSet <em>Braces Set</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Braces Set</em>' attribute.
   * @see #isBracesSet()
   * @generated
   */
  void setBracesSet(boolean value);

} // RefOrCall
