/**
 * generated by Xtext 2.20.0
 */
package org.mofgen.mGLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.mofgen.mGLang.MGLangPackage#getStringExpression()
 * @model
 * @generated
 */
public interface StringExpression extends EObject
{
} // StringExpression
