/**
 * generated by Xtext 2.20.0
 */
package org.mofgen.mGLang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Switch Case</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mofgen.mGLang.SwitchCase#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link org.mofgen.mGLang.SwitchCase#getCases <em>Cases</em>}</li>
 * </ul>
 *
 * @see org.mofgen.mGLang.MGLangPackage#getSwitchCase()
 * @model
 * @generated
 */
public interface SwitchCase extends Switch
{
  /**
   * Returns the value of the '<em><b>Attribute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' containment reference.
   * @see #setAttribute(RefOrCall)
   * @see org.mofgen.mGLang.MGLangPackage#getSwitchCase_Attribute()
   * @model containment="true"
   * @generated
   */
  RefOrCall getAttribute();

  /**
   * Sets the value of the '{@link org.mofgen.mGLang.SwitchCase#getAttribute <em>Attribute</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' containment reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(RefOrCall value);

  /**
   * Returns the value of the '<em><b>Cases</b></em>' containment reference list.
   * The list contents are of type {@link org.mofgen.mGLang.Case}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cases</em>' containment reference list.
   * @see org.mofgen.mGLang.MGLangPackage#getSwitchCase_Cases()
   * @model containment="true"
   * @generated
   */
  EList<Case> getCases();

} // SwitchCase
